# -*- coding: utf-8 -*-
"""Simple RAG Appllication.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uRyLykDF8CuPlXWhhydNwq_gBP9YIAVO
"""

!pip install langchain -qU
!pip install langchain-google-genai -qU
!pip install langchain-chroma -qU

# Import nessary libraries
import os
from google.colab import userdata

import os
from google import genai

# 1. Ensure your API key is set in the environment
# If you are in Colab, uncomment the next line and use userdata:
os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API')

# 2. Initialize the Google GenAI client
client = genai.Client()

# 3. Fetch and print all available models
print("Available Gemini Models:\n" + "-"*25)
for model in client.models.list():
    print(model.name)

"""Setup Gemini LLM"""

from langchain_google_genai import ChatGoogleGenerativeAI

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API')

model = ChatGoogleGenerativeAI (
    model = "gemini-2.5-flash",
    temperature = 0
)

"""Initialize Embessing Model"""

from langchain_google_genai import GoogleGenerativeAIEmbeddings
embeddings = GoogleGenerativeAIEmbeddings(model="gemini-embedding-2-preview")

"""Create and Embedd Documents"""

from langchain_core.documents import Document

documents = [
    # Your original examples (with updated metadata)
    Document(
        page_content="A bunch of scientists bring back dinosaurs and mayhem breaks loose.",
        metadata={"title": "Jurassic Park", "genre": "Sci-Fi", "year": 1993}
    ),
    Document(
        page_content="Leo DiCaprio gets lost in a dream within a dream within a dream within a...",
        metadata={"title": "Inception", "genre": "Sci-Fi/Action", "year": 2010}
    ),

    # New additions
    Document(
        page_content="A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
        metadata={"title": "The Matrix", "genre": "Sci-Fi", "year": 1999}
    ),
    Document(
        page_content="A young farm boy joins a rebellion to save a princess and destroy a massive, planet-killing space station.",
        metadata={"title": "Star Wars: Episode IV", "genre": "Space Opera", "year": 1977}
    ),
    Document(
        page_content="A wealthy family gets trapped in a flooded hotel with sharks, but no wait, that's not right. A giant ship hits an iceberg and sinks while a rich girl and a poor artist fall in love.",
        metadata={"title": "Titanic", "genre": "Romance/Drama", "year": 1997}
    ),
    Document(
        page_content="An aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        metadata={"title": "The Godfather", "genre": "Crime/Drama", "year": 1972}
    ),
    Document(
        page_content="A meek Hobbit and eight companions set out on a journey to destroy a powerful ring and save Middle-earth from the Dark Lord.",
        metadata={"title": "The Lord of the Rings: The Fellowship of the Ring", "genre": "Fantasy", "year": 2001}
    ),
    Document(
        page_content="A billionaire uses his wealth to dress up like a bat and punch criminals at night in a very gloomy city.",
        metadata={"title": "The Dark Knight", "genre": "Action/Superhero", "year": 2008}
    )
]

from langchain_chroma import Chroma

vector_store = Chroma.from_documents(
    documents = documents,
    embedding=embeddings,
)

"""Similarity Search"""

results = vector_store.similarity_search("red pill")

for result in results:
    print(result.page_content)
    print(result.metadata)

query_embeddins = embeddings.embed_query("red pill")

results = vector_store.similarity_search_by_vector(query_embeddins)

for result in results:
    print(result.page_content)
    print(result.metadata)

len(query_embeddins)

retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 1}
)

batch_results = retriever.invoke("red pill",)
for result in batch_results:
    print(result.page_content)
    print(result.metadata)

"""Create Prompt Template"""

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough

message = """
Answer this quection using the provided context only.

{quection}

Context:
{context}
"""

prompt = ChatPromptTemplate.from_messages(
    [
        ("human", message),
    ]
)

"""Chain Retriever and Prompt Template with LLM"""

chain = {"context": retriever, "quection": RunnablePassthrough()} | prompt | model

response = chain.invoke("give me an movie about pysics")
print(response.content)